server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5434/catalog_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: ""
    sql-migration-separator: "_"
    sql-migration-suffixes: .sql

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always